### ISSUE TITLE
src_template attached

### ISSUE THREAD

**Issue by Perrishnikov** [profscottpeterson/81228_Team2#1]
[srs_template.docx](https://github.com/profscottpeterson/81228_Team2/files/1335118/srs_template.docx)

**Comment by andrewmoule** [comment]
Here is the file that was typed up during conference room time.

[srs_template.docx](https://github.com/profscottpeterson/81228_Team2/files/1335283/srs_template.docx)

**Comment by Perrishnikov** [comment]
Unneeded; srs is now in the docs folder and under version control.
