### ISSUE TITLE
Create UI mockups

### ISSUE THREAD

**Issue by Perrishnikov** [profscottpeterson/81228_Team2#4]
Create mockups for each page/ panel of the app. Suggest to save the coding until the mockups are approved by the team.

**Comment by QuinnCCapelle** [comment]
![pizzaplanet login](https://user-images.githubusercontent.com/32101774/31152265-f1b1d3be-a860-11e7-8fe3-fffb6015b3ab.jpg)

**Comment by QuinnCCapelle** [comment]
![pizzaplanet login](https://user-images.githubusercontent.com/32101774/31152281-05b98212-a861-11e7-86f5-725cda3e3f16.jpg)
![pizzaplanet main](https://user-images.githubusercontent.com/32101774/31152285-07d6b61e-a861-11e7-8b72-b053c3d705f5.jpg)
![pizzaplanet select](https://user-images.githubusercontent.com/32101774/31152287-09eb3628-a861-11e7-8b74-50333d919d32.jpg)
