### ISSUE TITLE
Create app UML

### ISSUE THREAD

**Issue by Perrishnikov** [profscottpeterson/81228_Team2#6]
Would be nice to have a doc to reference for class construction.

**Comment by hwillgen** [comment]
This is the UML based on the MVC pattern
![pizzaplanetmvc](https://user-images.githubusercontent.com/32106606/31098732-4034326c-a789-11e7-93bb-f1be8c1de65a.png)

**Comment by Perrishnikov** [comment]
Looks great!

**Comment by Perrishnikov** [comment]
There is one thing that I noticed: we are going to need the View to send changes back to the controller. For example, in order for the pizza.setSize() to be called, the view will have to accept the Users input, send it to the controller, to update the pizza state/model. Can you somehow show that the PizzaView can call methods on the controller?
